// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type StorageRoom struct {
	ID        int32
	Name      pgtype.Text
	Number    pgtype.Int4
	Warehouse pgtype.Text
}

type Warehouse struct {
	ID       int32
	Name     string
	Address  string
	Ward     int32
	District string
	City     string
	Country  string
}
