// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

type StorageRoom struct {
	ID          int32
	Name        string
	Number      string
	WarehouseID int32
}

type Warehouse struct {
	ID       int64
	Name     string
	Address  string
	Ward     string
	District string
	City     string
	Country  string
}
