// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: storageroom.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStorageRoom = `-- name: CreateStorageRoom :one
INSERT INTO storage_room (
    name, number, warehouse
) VALUES (
    $1, $2, $3
) RETURNING id, name, number, warehouse
`

type CreateStorageRoomParams struct {
	Name      pgtype.Text
	Number    pgtype.Int4
	Warehouse pgtype.Text
}

func (q *Queries) CreateStorageRoom(ctx context.Context, arg CreateStorageRoomParams) (StorageRoom, error) {
	row := q.db.QueryRow(ctx, createStorageRoom, arg.Name, arg.Number, arg.Warehouse)
	var i StorageRoom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Number,
		&i.Warehouse,
	)
	return i, err
}

const deleteStorageRoom = `-- name: DeleteStorageRoom :exec
DELETE FROM storage_room
WHERE id = $1
`

func (q *Queries) DeleteStorageRoom(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteStorageRoom, id)
	return err
}

const getStorageRoom = `-- name: GetStorageRoom :one
SELECT id, name, number, warehouse FROM storage_room
WHERE id = $1
`

func (q *Queries) GetStorageRoom(ctx context.Context, id int32) (StorageRoom, error) {
	row := q.db.QueryRow(ctx, getStorageRoom, id)
	var i StorageRoom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Number,
		&i.Warehouse,
	)
	return i, err
}

const listStorageRoom = `-- name: ListStorageRoom :many
SELECT id, name, number, warehouse
FROM storage_room
LIMIT $1 OFFSET $2
`

type ListStorageRoomParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListStorageRoom(ctx context.Context, arg ListStorageRoomParams) ([]StorageRoom, error) {
	rows, err := q.db.Query(ctx, listStorageRoom, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StorageRoom
	for rows.Next() {
		var i StorageRoom
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Number,
			&i.Warehouse,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStorageRoom = `-- name: UpdateStorageRoom :one
UPDATE storage_room
SET name = $2,
    number = $3,
    warehouse = $4
WHERE id = $1
RETURNING id, name, number, warehouse
`

type UpdateStorageRoomParams struct {
	ID        int32
	Name      pgtype.Text
	Number    pgtype.Int4
	Warehouse pgtype.Text
}

func (q *Queries) UpdateStorageRoom(ctx context.Context, arg UpdateStorageRoomParams) (StorageRoom, error) {
	row := q.db.QueryRow(ctx, updateStorageRoom,
		arg.ID,
		arg.Name,
		arg.Number,
		arg.Warehouse,
	)
	var i StorageRoom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Number,
		&i.Warehouse,
	)
	return i, err
}
