// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: warehouse.sql

package models

import (
	"context"
)

const createWarehouse = `-- name: CreateWarehouse :one
INSERT INTO warehouse (
    name, address, ward, district, city, country
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, name, address, ward, district, city, country
`

type CreateWarehouseParams struct {
	Name     string
	Address  string
	Ward     string
	District string
	City     string
	Country  string
}

func (q *Queries) CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (Warehouse, error) {
	row := q.db.QueryRow(ctx, createWarehouse,
		arg.Name,
		arg.Address,
		arg.Ward,
		arg.District,
		arg.City,
		arg.Country,
	)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Ward,
		&i.District,
		&i.City,
		&i.Country,
	)
	return i, err
}

const deleteWarehouse = `-- name: DeleteWarehouse :exec
DELETE FROM warehouse
WHERE id = $1
`

func (q *Queries) DeleteWarehouse(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteWarehouse, id)
	return err
}

const getWarehouse = `-- name: GetWarehouse :one
SELECT id, name, address, ward, district, city, country FROM warehouse
WHERE id = $1
`

func (q *Queries) GetWarehouse(ctx context.Context, id int64) (Warehouse, error) {
	row := q.db.QueryRow(ctx, getWarehouse, id)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Ward,
		&i.District,
		&i.City,
		&i.Country,
	)
	return i, err
}

const listWarehouse = `-- name: ListWarehouse :many
SELECT id, name, address, ward, district, city, country
FROM warehouse
LIMIT $1 OFFSET $2
`

type ListWarehouseParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListWarehouse(ctx context.Context, arg ListWarehouseParams) ([]Warehouse, error) {
	rows, err := q.db.Query(ctx, listWarehouse, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Warehouse
	for rows.Next() {
		var i Warehouse
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Ward,
			&i.District,
			&i.City,
			&i.Country,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWarehouse = `-- name: UpdateWarehouse :one
UPDATE warehouse
SET name = $2,
    address = $3,
    ward = $4,
    district = $5,
    city = $6,
    country = $7
WHERE id = $1
RETURNING id, name, address, ward, district, city, country
`

type UpdateWarehouseParams struct {
	ID       int64
	Name     string
	Address  string
	Ward     string
	District string
	City     string
	Country  string
}

func (q *Queries) UpdateWarehouse(ctx context.Context, arg UpdateWarehouseParams) (Warehouse, error) {
	row := q.db.QueryRow(ctx, updateWarehouse,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Ward,
		arg.District,
		arg.City,
		arg.Country,
	)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Ward,
		&i.District,
		&i.City,
		&i.Country,
	)
	return i, err
}
